services:
  sure-sync:
    image: ghcr.io/shrestha-bishal/sure-sync:latest
    container_name: sure-sync
    env_file:
      - .env
    volumes:
      - ${CONSUME_PATH}:/app/consume
      - ${CONSUME_PATH}/processed:/app/processed
      - ./account-mapping.yml:/app/account-mapping.yml:ro
    restart: unless-stopped